services:
  # -------------------- FRONTEND: React (Vite) ---------------------
  - type: static
    name: seekkrr-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    # --- OPTION A: Use env var in React for API base URL
    envVars:
      - key: VITE_API_BASE_URL
        value: https://api.seekkrr.com   # after backend deploy, paste the seekkrr-api URL here
    # --- OPTION B (alternative to env var): add a rewrite for /api/*
    routes:
      - type: rewrite
        source: /api/*
        destination: https://api.seekkrr.com /api/:splat
